### PR TITLE
Create config.schema.json

### PR DESCRIPTION
**Pull request by NikoGrano**

### CODE REVIEW

**Comment by NikoGrano** [comment]
closes #8

**Comment by NikoGrano** [comment]
@majkrzak plz review

**Review by majkrzak — CHANGES_REQUESTED** [review]
Please do not post spam. File is invalid, autogenerated and nonsense.

**Comment by NikoGrano** [comment]
@majkrzak While you don't specify schema requirements, this is what you get. In that case, please do it yourself, referencing your private message.

**Comment by majkrzak** [comment]
spam

**Pull request closed without merging**
